version: '3.8'
services:
  qinglong-debian:
    image: whyour/qinglong:debian
    container_name: qinglong-debian
    restart: unless-stopped
    ports:
      - "${TRIM_SERVICE_PORT}:5700"
    volumes:
      - "/${TRIM_APPDEST_VOL}/@appshare/${TRIM_APPNAME}:/ql/data"